### ISSUE TITLE
Add a reset native function

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba-target-thymio2#10]
@motib has suggested to add a reset output native function doing the followings:
```
call sound.system(-1)
call leds.top(0,0,0)
call leds.bottom.left(0,0,0)
call leds.bottom.right(0,0,0)
call leds.circle(0,0,0,0,0,0,0,0)
```

In addition, I suggest that, if implemented, such a function resets the IR communication (see issues #8 and #9). Technically, there might be an internal function called both from the initialization code and from the proposed native function.

**Comment by mbonani** [comment]
call sound system(-1) should not be in this reset. It is used to mute normal system  sound when we press buttons. It was implement in VPL to not make mistake using the micro card. 
OK for the others.

**Comment by mbonani** [comment]
Another point to discuss is also what to do with internal "behvior" like the blowing of the leds from IR sensors. One time you use the "call leds.ir.prox(.. )" it stop the blowing behavior. Should we reinitialize it in this reset? It the same for the sound.

**Comment by stephanemagnenat** [comment]
Your last point is interesting. Yes I suggest that the reset also re-initialize these to the startup behaviour.

**Comment by mbonani** [comment]
implement in commit 02a640d

**Comment by mbonani** [comment]
finally this function is not need with the clean VM when loading or reseting
