### ISSUE TITLE
Event flags are not cleared when VM is reset

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba-target-thymio2#16]
The array `events_flags` should be cleared upon calling `AsebaVMResetCB()`. This is likely to be the cause of bug aseba-community/aseba#531.

**Comment by mbonani** [comment]
fix in a08f8e0

**Comment by stephanemagnenat** [comment]
Good! Please close the corresponding Aseba issue if this fix also corrects it. Thank you :-)
