### ISSUE TITLE
New native function to retrieve the duration of a recorded sound

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba-target-thymio2#21]
To make sounds available in VPL, it would be useful to have a native function, for instance `sound.duration`, that returns the duration of a given sound stored on the SD card.

**Comment by mbonani** [comment]
is the actual event sound.finished not sufficient?

**Comment by stephanemagnenat** [comment]
> is the actual event sound.finished not sufficient?

Not really, because you would like to show the duration in the editor, without having to play the sound.

**Comment by mbonani** [comment]
when we record sounds we store in the .wav header  the size of the sample counter.  So I propose to read only to the recordet sound files rN.wav sizes.  The problem is that its is in long format 32 bits

**Comment by stephanemagnenat** [comment]
We could easily have a native function that parses the header, and transforms the duration into 10th of seconds.

**Comment by mbonani** [comment]
sound.duration(N, ds) 
Give sound duration in 1/10 sec of rN.wav

**Comment by mbonani** [comment]
implement in d2be7683a437f20433fd88efc28a1011781be30f

**Comment by mbonani** [comment]
thanks for comments new implementation here ebf4bf656daeb1dd2b64cc6c43859a841a43f813
