### ISSUE TITLE
Add a way to reset the behaviour of sensor LEDs

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba-target-thymio2#27]
When a Thymio is booted, sensor LEDs indicate the activity of the sensor. However, once one of these LED has been controlled from Aseba, this behaviour is disabled, and the only way to retrieve it is to restart the robot.

This is a limitation, for instance if we want to display an error status in VPL using these LEDs, and then revert to the default behaviour when the program has been corrected.

I suggest to add either a native function or a variable flag to re-enabled the default behaviour. It is fine if it does so for all LEDs.

**Comment by mbonani** [comment]
This is implemented in firmware 11, when you load or reset the robot basic behavior are re enabled.

**Comment by stephanemagnenat** [comment]
perfect ;)

**Comment by stephanemagnenat** [comment]
firmware 11 is not released yet, right?

**Comment by mbonani** [comment]
not release in betaversion
