### ISSUE TITLE
About which sound does sound.duration reports the duration?

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba-target-thymio2#33]
Does it check `Rx.wav` or `Px.wav`? For the use in VPL mobile, it is important that it provides at least `Rx.wav` for interactive sound recording on the robot.

**Comment by mbonani** [comment]
Rx.wav as we discuss you wanted for interactive recording

**Comment by stephanemagnenat** [comment]
Perfect, thank you for the quick answer.
