### ISSUE TITLE
Tap event is much too sensitive

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba-target-thymio2#7]
As discussed in the corresponding issue on the Aseba tracker aseba-community/aseba#386, the threshold for generated tap event should be revisited.

**Comment by stephanemagnenat** [comment]
This cannot be solved with current hardware because this processing is done in the electronics of the accelerometer.

**Comment by retornaz** [comment]
Huh, read the MMA7660 Datasheet ... Hint: register PDET, file mma7660.c, line 165 ...

**Comment by stephanemagnenat** [comment]
Hum, Michael lied to me then ;-)

**Comment by riedo** [comment]
We will look into this with Michael for the next firmware release. We need to set priorities in what we want to detect or not and make tests with the PDTH value. For example, a young child should be able to trigger the tap event without hitting too hard, the robot should detect when it hits a wall at a certain speed, the motors should not trigger the tap event etc... So please think about such a requirements list and we'll try our best.

**Comment by mbonani** [comment]
What I have said that detection is inside the chip and parameters are hardcoded in the firmware. So before saying that I am a lyer....

**Comment by stephanemagnenat** [comment]
> So before saying that I am a liar....

that was a (bad) joke, please excuse me if you felt offended, it was not the intention.

**Comment by mbonani** [comment]
No no absolutly not I understand that was a joke... just be careful on
public forums 😉
Le 18 août 2015 15:55, "Stéphane Magnenat" <notifications@github.com> a
écrit :

**Comment by mbonani** [comment]
The original demand is that you can move with Thymio without firing the tap event.
The motors when turning make vibrations. So actual tap event is fired all time. 
I test several solution to solve this problem, make the accelerometer less sensitive and increase re-bounce count. Both parameter are fix in the firmware. Threshold became so high that than to make a tap you have to really hit strongly the robot.
Finally I discover that vibration are mostly in one direction (laterally, in the same axis of wheel). So final solution is to disable X axis for tap detection. Sensitivity is the same as before, I just increase à little the re-boucne count. 
Final behaviour: you can still detect tap, you can run full speed (500) and also detect when robot hit a wall.
In commit  e927408

**Comment by mbonani** [comment]
in last merge please close
