### ISSUE TITLE
ir-comm is not shut off living friendly behavior

### ISSUE THREAD

**Issue by mbonani** [aseba-community/aseba-target-thymio2#9]

**Comment by stephanemagnenat** [comment]
This seems a duplication of issue #8.

**Comment by mbonani** [comment]
not exactly, ircomm should be shut down living friendly mode, robot as not to communicate in other modes and it is independent if people program and connect the robot.

**Comment by stephanemagnenat** [comment]
I see, I agree.

**Comment by mbonani** [comment]
it seems that it is done for a long time.... 
proably a bad understanding of a user case.

**Comment by mbonani** [comment]
in fact when vm is launch when friendly behavior  is active, ir comm is not disable. 
Fix in commit 574b159
